Repository ishraqn/CGC-DataVizTool, pull requests merged in 2024-03, with the labels that each got.

#42 38 remove file implementation
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ConfirmationDialog.tsx
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#44 Relocate Color Picker for Sidebar Integration
  client/src/components/ColorPickerComponent.tsx
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
  client/src/utils/colourUtils.ts
Labels: frontend

#46 Implemented Region Toggles Feature with Dynamic Bound Fitting
  client/src/App.tsx
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#47 Fetch and app refresh optimizations
  client/src/App.tsx
  server/src/controller/csvController.ts
  server/src/controller/fileController.ts
  server/src/controller/geoController.ts
  server/src/controller/mapController.ts
  server/src/index.ts
  server/src/routes/fileRoutes.ts
  server/src/utils/csv2GeojsonUtils.ts
  server/src/utils/geoSpatialJoinUtil.ts
Labels: enhancement, comboend

#48 37 prompts for dataformat
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/components/GuideTooltip.css
  client/src/components/GuideTooltip.tsx
  client/src/components/sidebar.css
  client/src/components/uploadForm.css
  client/src/components/uploadForm.tsx
Labels: frontend

#49 Fix sidebar clicking issues, Add Selection Toggles
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
Labels: enhancement, frontend

#51 Update colour picker
  client/src/components/ColorPickerComponent.tsx
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
  client/src/utils/colourUtils.ts
Labels: enhancement, frontend
