Repository ishraqn/CGC-DataVizTool, pull requests merged in 2024-04, with the labels that each got.

#56 Implement province select
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#55 Implement Hex code input and styling
  client/src/components/ColorPickerComponent.css
  client/src/components/ColorPickerComponent.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#53 Implement nonzero sample select
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.tsx
Labels: frontend

#57 Feature/update download
  client/src/App.tsx
  client/src/components/geoJSONMap.tsx
  client/src/contexts/toggleContext.tsx
  server/src/controller/mapController.ts
  server/src/utils/renderMapUtil.ts
Labels: comboend

#58 Optimize file processing
  server/src/controller/csvController.ts
  server/src/controller/fileController.ts
  server/src/controller/geoController.ts
  server/src/utils/csv2GeojsonUtils.ts
  server/src/utils/geoSpatialJoinUtil.ts
Labels: backend

#59 fix bug that keeps hex error message visible
  client/src/components/ColorPickerComponent.tsx
Labels: frontend

#61 Tile Layer Toggle
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#62 Update/optimize title
  client/src/components/GuideTooltip.tsx
  client/src/components/TitleComponent.tsx
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
  server/src/controller/fileController.ts
  server/src/index.ts
  server/src/routes/fileRoutes.ts
Labels: comboend

#63 Update/optimize title
  client/src/App.tsx
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: comboend

#64 Update/multiple works
  client/src/App.tsx
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.tsx
  client/src/contexts/toggleContext.tsx
Labels: frontend

#65 Update download
  client/src/App.tsx
  client/src/components/geoJSONMap.tsx
  client/src/contexts/toggleContext.tsx
  server/src/controller/mapController.ts
  server/src/utils/renderMapUtil.ts
Labels: comboend

#66 Update/final updates
  client/package-lock.json
  client/package.json
  client/src/components/geoJSONMap.tsx
  client/src/contexts/toggleContext.tsx
  server/src/utils/renderMapUtil.ts
Labels: comboend
