Repository ishraqn/CGC-DataVizTool, pull requests merged in 2024-02, with the labels that each got.

#9 Add custom mapping options and Style Map
  .gitignore
  client/src/App.css
  client/src/components/geoJSONMap.tsx
Labels: enhancement

#10 backend routes updates-more modularity
  server/src/controller/fileController.ts
  server/src/index.ts
  server/src/middleware/sessionsMiddleware.ts
  server/src/middleware/uploadMiddleware.ts
  server/src/routes/fileRoutes.ts
  server/src/routes/shapefileRoutes.ts
Labels: enhancement

#11 Upload csv feature
  .gitignore
  client/index.html
  client/src/App.tsx
  client/src/components/uploadForm.tsx
  server/package-lock.json
  server/package.json
  server/src/controller/fileController.ts
  server/src/middleware/uploadMiddleware.ts
  server/src/routes/fileRoutes.ts
Labels: enhancement

#23 Add Cleanup Util for Temp Files
  client/src/App.tsx
  server/src/controller/fileController.ts
  server/src/index.ts
  server/src/middleware/uploadMiddleware.ts
  server/src/routes/fileRoutes.ts
  server/src/utils/tempfileCleanupUtil.ts
Labels: enhancement, backend

#28 Update and Fixes to Last CSV Commit
  server/package-lock.json
  server/package.json
  server/src/controller/csvController.ts
  server/src/controller/fileController.ts
  server/src/routes/fileRoutes.ts
  server/src/utils/csv2GeojsonUtils.ts
Labels: bug, backend

#29 add sidebar, site styling, filter groups, leaflet container changes
  client/src/App.css
  client/src/App.tsx
  client/src/components/geoJSONMap.css
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/index.css
Labels: enhancement, frontend

#30 add routes, controls, utils for geo spatial functions,calculations. a…
  client/src/App.tsx
  client/src/components/geoJSONMap.tsx
  client/src/components/uploadForm.tsx
  server/package-lock.json
  server/package.json
  server/src/controller/fileController.ts
  server/src/controller/geoController.ts
  server/src/index.ts
  server/src/middleware/sessionsMiddleware.ts
  server/src/routes/fileRoutes.ts
  server/src/routes/geoRoutes.ts
  server/src/utils/geoSpatialJoinUtil.ts
  server/tsconfig.json
Labels: enhancement, comboend

#32 add sidebar toggle context, file switching, fix and update routes.
  client/src/App.tsx
  client/src/components/sidebar.tsx
  client/src/components/uploadForm.tsx
  client/src/contexts/toggleContext.tsx
  client/src/contexts/useToggle.tsx
  client/src/main.tsx
  server/src/controller/fileController.ts
  server/src/controller/geoController.ts
  server/src/middleware/uploadMiddleware.ts
  server/src/routes/fileRoutes.ts
Labels: enhancement, comboend

#33 Revert "4 colour customization options"
  client/package-lock.json
  client/package.json
  client/src/components/ColorPickerComponent.tsx
  client/src/components/geoJSONMap.tsx
  client/src/utils/geoJSONUtils.ts
  package.json
  server/package.json
  server/src/data/default/simplified/default-simplified.geojson
Labels: bug

#34 Download Functionality and Site Styling
  client/src/App.css
  client/src/App.tsx
  client/src/components/geoJSONMap.css
  client/src/components/sidebar.tsx
  client/src/components/uploadForm.css
  client/src/components/uploadForm.tsx
  client/src/contexts/toggleContext.tsx
  client/src/index.css
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/controller/mapController.ts
  server/src/index.ts
  server/src/routes/mapRoutes.ts
  server/src/utils/renderMapUtil.ts
Labels: enhancement, comboend

#35 Enhance Site Styling and Refine Map Download Colors
  client/src/components/geoJSONMap.css
  client/src/components/geoJSONMap.tsx
  client/src/components/sidebar.css
  client/src/components/sidebar.tsx
  client/src/components/uploadForm.css
  server/src/utils/renderMapUtil.ts
Labels: enhancement, comboend
